export const LOGIN_URL = 'https://www.codingkaro.in/api/web/login'
export const SIGNUP_URL = 'https://www.codingkaro.in/user/signup'

export const APP_NAME = 'Connect-Engage'
export const LOGOUT_COMMAND = 'logout'
export const REFRESH_COMMAND = 'refresh'
export const UUID = 'uuid'
export const EMAIL = 'email'
export const TOKEN = 'token'
export const EXPIRY = 'expiry'
export const SAVE_CREDENTIALS_COMMAND = 'saveCredentials'
export const CHECK_AUTH_STATUS_COMMAND = 'checkAuthStatus'
